### ISSUE TITLE
Make it (re)usable in another code base, without need for a global installation

### ISSUE THREAD

**Issue by wolframkriesing** [compose-us-research/docker-box#1]
I was about to use it in a project, because I like the idea.
But I don't like the idea of having to have another global installation of a tool, which most people don't have (yet). What about publishing it as a npm package (and for whatever other bundler/packager) too, so it can be checked in as a dependency of a code base and I can just do `./node_modules/.bin/docker-box` to run it?

**Comment by Narigo** [comment]
Thanks for sharing this idea!

Right now, `docker-box` is a shell script, so more or less Linux/Mac only. I could write a wrapper in Node to make the commands but then I'd need to have `npm`/`node` installed globally. I actually don't have that globally on my computer since I use `docker-box` as the global tool already...

It's a bit of a chicken/egg problem I'm unsure how to solve. Yes, you could have it as a dev dependency in your node project, but then, when you do `npm install`, it will install all the (possible malicious) dependencies as well, defeating the main sandboxing purpose, doesn't it?

**Comment by wolframkriesing** [comment]
oh true,  i  have a local docker currently, that's why i thought it would be possible, but you are right, it would defeat the purpose ... I will think  about it again.
I am struggling with the global depenendency, but you are right ... chicken+egg
